/*
* generated by Xtext
*/
package de.grammarcraft.csflow.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class FlowOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
