/*
* generated by Xtext
*/
package de.grammarcraft.flow.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

import de.grammarcraft.flow.flow.Flow;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class FlowDescriptionLabelProvider extends DefaultDescriptionLabelProvider {

	String text(Flow ele) {
		  return "Flow " + ele.getName();
		}

/*
	//Labels and icons can be computed like this:
	
	String text(IEObjectDescription ele) {
	  return "my "+ele.getName();
	}
	 
    String image(IEObjectDescription ele) {
      return ele.getEClass().getName() + ".gif";
    }	 
*/

}
