/*
* generated by Xtext
*/
package de.grammarcraft.csflow.ui.contentassist;

import de.grammarcraft.csflow.ui.contentassist.AbstractFlowProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FlowProposalProvider extends AbstractFlowProposalProvider {

}
